name = "admin-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
GH_OWNER = "LiangFeng111"
GH_REPO = "xxx"
GH_BRANCH = "master"

[dev.vars]
# You can set these for local development in .dev.vars file
GH_OWNER = "LiangFeng111"
GH_REPO = "xxx"
GH_BRANCH = "master"
